const valueType = {
  NUMBER: 'number',
  PERCENTAGE: 'percentage',
  CURRENCY: 'currency',
};

const constants = {
  TIMEFRAME: {
    YESTERDAY: 'yesterday',
    TODAY: 'today',
    LAST_7_DAYS: 'last7days',
    LAST_30_DAYS: 'last30days',
    THIS_MONTH: 'thisMonth',
    LAST_MONTH: 'lastMonth',
    LIFETIME: 'lifetime',
  },
  STATUS: {
    ACTIVE: 'active',
    INACTIVE: 'inactive',
    ALL: 'all',
  },
  FREQUENCY: {
    HOURLY: 'hourly',
    DAILY: 'daily',
  },
  VALUE_TYPE: valueType,
  KPI: {
    IMPRESSIONS: {
      key: 'IMPRESSIONS',
      name: 'Impressions',
      color: 'rgba(255, 147, 138, 1)',
      colorHovered: 'rgba(255, 147, 138, 0.1)',
      enabled: true,
      valueType: valueType.NUMBER,
    },
    CLICKS: {
      key: 'CLICKS',
      name: 'Clicks',
      color: 'rgba(202, 153, 255, 1)',
      colorHovered: 'rgba(202, 153, 255, 0.1)',
      enabled: true,
      valueType: valueType.NUMBER,
    },
    CTR: {
      key: 'CTR',
      name: 'CTR',
      color: 'rgba(255, 201, 141, 1)',
      colorHovered: 'rgba(255, 201, 141, 0.1)',
      enabled: true,
      valueType: valueType.PERCENTAGE,
    },
    CONVERSION: {
      key: 'CONVERSION',
      name: 'Conversion',
      color: 'rgba(255, 153, 200, 1)',
      colorHovered: 'rgba(255, 153, 200, 0.1)',
      enabled: true,
      valueType: valueType.NUMBER,
    },
    CVR: {
      key: 'CVR',
      name: 'CVR',
      color: 'rgba(122, 200, 168, 1)',
      colorHovered: 'rgba(122, 200, 168, 0.1)',
      enabled: true,
      valueType: valueType.PERCENTAGE,
    },
    CPM: {
      key: 'CPM',
      name: 'CPM',
      color: 'rgba(122, 200, 168, 1)',
      colorHovered: 'rgba(122, 200, 168, 0.1)',
      enabled: false,
      valueType: valueType.CURRENCY,
    },
    CPC: {
      key: 'CPC',
      name: 'CPC',
      color: 'rgba(122, 200, 168, 1)',
      colorHovered: 'rgba(122, 200, 168, 0.1)',
      enabled: false,
      valueType: valueType.CURRENCY,
    },
    CPO: {
      key: 'CPO',
      name: 'CPO',
      color: 'rgba(122, 200, 168, 1)',
      colorHovered: 'rgba(122, 200, 168, 0.1)',
      enabled: false,
      valueType: valueType.CURRENCY,
    },
    COST: {
      key: 'COST',
      name: 'Cost',
      color: 'rgba(122, 200, 168, 1)',
      colorHovered: 'rgba(122, 200, 168, 0.1)',
      enabled: false,
      valueType: valueType.CURRENCY,
    },
    ORDER_VALUE: {
      key: 'ORDER_VALUE',
      name: 'Order value',
      color: 'rgba(122, 200, 168, 1)',
      colorHovered: 'rgba(122, 200, 168, 0.1)',
      enabled: false,
      valueType: valueType.CURRENCY,
    },
    MARGIN: {
      key: 'MARGIN',
      name: 'Margin',
      color: 'rgba(122, 200, 168, 1)',
      colorHovered: 'rgba(122, 200, 168, 0.1)',
      enabled: false,
      valueType: valueType.CURRENCY,
    },
    ROI: {
      key: 'ROI',
      name: 'ROI',
      color: 'rgba(122, 200, 168, 1)',
      colorHovered: 'rgba(122, 200, 168, 0.1)',
      enabled: false,
      valueType: valueType.PERCENTAGE,
    },
  },
};

export default constants;
