const valueType = {
  NUMBER: 'number',
  PERCENTAGE: 'percentage',
  CURRENCY: 'currency',
};

const constants = {
  ERROR_TYPE: {
    SESSION_EXPIRED: 'session_expired',
    SERVER_ERROR: 'server_error',
  },
  FALLBACK_LOCALE: 'de',
  TIMEFRAME: {
    YESTERDAY: 'yesterday',
    TODAY: 'today',
    LAST_7_DAYS: 'last7days',
    LAST_30_DAYS: 'last30days',
    THIS_MONTH: 'thisMonth',
    LAST_MONTH: 'lastMonth',
    LIFETIME: 'lifetime',
  },
  STATUS: {
    ACTIVE: 'active',
    INACTIVE: 'inactive',
    ALL: 'all',
  },
  FREQUENCY: {
    HOURLY: 'hourly',
    DAILY: 'daily',
  },
  VALUE_TYPE: valueType,
  CAMPAIGN_DATA_FIXED_HEADERS: {
    STATUS: 'status',
    CAMPAIGN: 'campaign',
  },
  KPI: {
    IMPRESSIONS: {
      key: 'impressions',
      name: 'Impressions',
      color: 'rgba(255, 147, 138, 1)',
      colorHovered: 'rgba(255, 147, 138, 0.1)',
      enabled: true,
      valueType: valueType.NUMBER,
    },
    CLICKS: {
      key: 'clicks',
      name: 'Clicks',
      color: 'rgba(202, 153, 255, 1)',
      colorHovered: 'rgba(202, 153, 255, 0.1)',
      enabled: true,
      valueType: valueType.NUMBER,
    },
    CTR: {
      key: 'ctr',
      name: 'CTR',
      color: 'rgba(255, 201, 141, 1)',
      colorHovered: 'rgba(255, 201, 141, 0.1)',
      enabled: true,
      valueType: valueType.PERCENTAGE,
    },
    CONVERSION: {
      key: 'orders',
      name: 'Conversion',
      color: 'rgba(255, 153, 200, 1)',
      colorHovered: 'rgba(255, 153, 200, 0.1)',
      enabled: true,
      valueType: valueType.NUMBER,
    },
    CVR: {
      key: 'cvr',
      name: 'CVR',
      color: 'rgba(122, 200, 168, 1)',
      colorHovered: 'rgba(122, 200, 168, 0.1)',
      enabled: true,
      valueType: valueType.PERCENTAGE,
    },
    CPM: {
      key: 'cpm',
      name: 'CPM',
      color: 'rgba(122, 200, 168, 1)',
      colorHovered: 'rgba(122, 200, 168, 0.1)',
      enabled: false,
      valueType: valueType.CURRENCY,
    },
    CPC: {
      key: 'cpc',
      name: 'CPC',
      color: 'rgba(122, 200, 168, 1)',
      colorHovered: 'rgba(122, 200, 168, 0.1)',
      enabled: false,
      valueType: valueType.CURRENCY,
    },
    CPO: {
      key: 'cpo',
      name: 'CPA',
      color: 'rgba(122, 200, 168, 1)',
      colorHovered: 'rgba(122, 200, 168, 0.1)',
      enabled: false,
      valueType: valueType.CURRENCY,
    },
    COST: {
      key: 'spend',
      name: 'Cost',
      color: 'rgba(122, 200, 168, 1)',
      colorHovered: 'rgba(122, 200, 168, 0.1)',
      enabled: false,
      valueType: valueType.CURRENCY,
    },
    ORDER_VALUE: {
      key: 'orderValue',
      name: 'Order value',
      color: 'rgba(122, 200, 168, 1)',
      colorHovered: 'rgba(122, 200, 168, 0.1)',
      enabled: false,
      valueType: valueType.CURRENCY,
    },
    MARGIN: {
      key: 'margin',
      name: 'Margin',
      color: 'rgba(122, 200, 168, 1)',
      colorHovered: 'rgba(122, 200, 168, 0.1)',
      enabled: false,
      valueType: valueType.CURRENCY,
    },
    ROI: {
      key: 'roi',
      name: 'ROI',
      color: 'rgba(122, 200, 168, 1)',
      colorHovered: 'rgba(122, 200, 168, 0.1)',
      enabled: false,
      valueType: valueType.PERCENTAGE,
    },
  },
};

export default constants;
